### ISSUE TITLE
Overriding icons 

### ISSUE THREAD

**Issue by aliogaili** [twisty/formsy-react-components#124]
Is it possible to pass the icons as a prop? 

For example, when an input is invalid, there is an X on the right corner of the input field that uses 'glyphicon'. Suppose I want to use other icon set, is it possible to provide a mechanism for overriding this class? 

<img width="1361" alt="screen shot 2018-03-26 at 11 44 39 am" src="https://user-images.githubusercontent.com/1675307/38017051-fdfbeb4a-3281-11e8-8c13-1acadade8c97.png">

**Comment by twisty** [comment]
Hi, I see what you mean... At the moment it isn't possible to pass the icon as a prop. I don't think I'll be adding this either, because I'd prefer to keep the API minimal and a higher priority is to rewrite for Bootstrap 4. I notice Bootstrap 4 no longer uses these icon overlays.

It could be a bit tricky, but I guess you could use the CSS cascade to overwrite the glyphicon with another icon.
