### ISSUE TITLE
formsy-react@0.18.0

### ISSUE THREAD

**Issue by sveip** [twisty/formsy-react-components#65]
Hi, I updated formsy-react to 0.18.0 to make it satisfied with react 15. The problem now is that formsy-react-components does not work anymore. It might well be something I'm doing wrong, so just let me know if there is any info that I can give that might be helpful.

**Comment by twisty** [comment]
Hi @petersvei, I haven't had a chance to try this with `formsy-react` v0.18 yet.

However, I've had success using this alongside `react` v15 with `formsy-react` v0.17. (npm will warn about an unsatisfied peer dependency on react 0.14, but if you use npm v3.x it doesn't try and install peer dependencies, so it'll be okay).

You say it doesn't work -- what happened / didn't happen? Did the form render? Any errors in the browser console?

**Comment by petersvei** [comment]
Thanks for you lightning fast response @twisty !

Same here, it was working fine with `formsy-react@0.17` except the unmet dep. warning.

The problem I experience when I upgrade is that the properties of the inputs seems not to be defined. If I try to set `this.refs.form.inputs.name.setValue` i get an error that it is undefined. The input is created like this:

`Input
              layout="vertical"
              name="my_name"
              type="text"
              label="Number of Channels"
              validations={{ validate: this.validateNumChan }}
            />`

This worked fine with `formsy-react@0.17.0` (which I know is a bad indicator.)

**Comment by twisty** [comment]
Hi, I've had a quick look and have observed this:

* in formsy-react@0.17 `form.inputs` returned an object, keyed by the `formsy.mixin` "`name`" prop.
* in formsy-react@0.18 `form.inputs` returns an array.

So it looks like this is a `formsy-react` change (is `Formsy.Form.inputs` listed as a public API? -- I don't think so?).

A workaround may be to set a React `ref` on the form components you need to track and use those instead, instead of relying `form.inputs`.

I'm going to close this because I don't think it is a `FRC` problem.

Good luck with sorting it out though!

**Comment by twisty** [comment]
Change was in: https://github.com/christianalfoni/formsy-react/commit/7481b6da645329605a4568e28dbfe82d902ae400

See https://github.com/christianalfoni/formsy-react/issues/267

**Comment by sveip** [comment]
Thanks, you are absolutely right. I changed my app to use 'reset(values)' to set the input fields instead, so that I don't have to rely on 'form.inputs' anymore.
