### ISSUE TITLE
Input is changing a uncontrolled input of type text to be controlled

### ISSUE THREAD

**Issue by FutureKode** [twisty/formsy-react-components#66]
`Input is changing a uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

This happens on a few of my forms.. not sure why

**Comment by twisty** [comment]
All of the form elements within `formsy-react-components` are controlled components, maybe you are switching them to an uncontrolled components by using `undefined` or `null` as values?

See:

* http://facebook.github.io/react/tips/controlled-input-null-value.html
* https://github.com/christianalfoni/formsy-react/issues/332

**Comment by FutureKode** [comment]
Ah I see now in the source that value="" is passed to <Input /> :)

**Comment by twisty** [comment]
To clarify: if you initially pass `undefined` or `null` as the value prop, the component starts life as an "uncontrolled" component. Once you interact with the component, we set a value and react changes it to a "controlled" component, and issues the warning.

The `dev` branch (alpha quality) has better proptype checking, so we should get earlier warnings about this in the future.

**Comment by clindsey** [comment]
I had this warning message coming up for me when `initialValues` were empty and `format` returned `undefined`; the fix was to have `format` return `''` by default

**Comment by khushi511** [comment]
![image](https://cloud.githubusercontent.com/assets/10815258/24249930/170746de-0ffb-11e7-83b8-e6b95f8caeb1.png)

**Comment by stevematdavies** [comment]
This is an utterly obscure and nonsensical error, it really doesn't help with most solutions. Im using Material UI for react and I'm using reject /  accept buttons to close a dialog ( using redux to update the state accordingly) I have this warning, and I cannot get rid of it. Perhaps a better explanation of this controlled warning instead of more cryptic solutions?

**Comment by twisty** [comment]
Hi @stevematdavies — it is React that is raising this warning, we don't have any control over the wording. If you follow the advice set out above, it is avoidable. That said, I will add a note to the docs that we are dealing with controlled components, and that you shouldn't set a `null` or `undefined` initial state.

It's not clear to me how you're using `formsy-react-components` in your project. If you can't get to the bottom of this problem, report back with more detail or a code example and we'll try to help.

**Comment by Dhrumil1808** [comment]
I am trying to get rid of this error. I am using an input form with two text boxes and I have initialized their state's as an empty string. But still, React is raising this warning for one text box and thus, I am unable to update that textbox.  Can anybody suggest me an alternative solution?

**Comment by abhijitrakas** [comment]
Hi @Dhrumil1808 sorry for late reply here is my code example to remove this error

`class DemoPage extends React.Component
{
	constructor(props) {
		super(props);
		this.handleClick = this.handleClick.bind(this);
		this.handleInptChange = this.handleInptChange.bind(this);
		this.state = {isToggleOn: true, input1: '', input2: ''};
	}


	handleClick() {
	    this.setState(prevState => ({
	      	isToggleOn: !prevState.isToggleOn
	    }));
  	}

  	handleInptChange(event) {
  		this.setState({[event.target.name]: event.target.value});
  	}

	render() {
		return (
			React.createElement(
				'h1',
				null,
				'You are now on Demo Page!',
				React.createElement(
					'button',
					{onClick: this.handleClick},
					(this.state.isToggleOn) ? 'ON' : 'OFF'
				),
				React.createElement(
					'input',
					{type: 'text', onChange: this.handleInptChange, name: 'input1', value: this.state.input1},
				),
				React.createElement(
					'input',
					{type: 'text', onChange: this.handleInptChange, name: 'input2', value: this.state.input2},
				)
			)
		);
	}
}

export default DemoPage;`

let me know if you still facing same error.

**Comment by stevematdavies** [comment]
I still have this error now in React 16, and I cannot get rid of it. I am using MaterialUI and I am adding text box values if the user has chosen to save them in browserStorage (a remember me functionality). If the user has not selected they are initially undefined, (setting an empty string prevents the input boxes from being used at all.)


Here is a snippet from the Login (Im also using redux) ,props.credentials is gotten from localStorage, and mappedTo Props via redux-connect

 

```
render() {

 const { email, password } = (this.props.remember && this.props.credentials)
                                        ? this.props.credentials 
                                        : { email: undefined, password: undefined };

  return (
.....
<TextField
           floatingLabelText="Password"
            name="password"
            type="password"
            value={password} // I'm assuming here is the issue (its either populated or undefined)
            className="login-password"
            required="required"
             fullWidth={true}
             onBlur={this.harvestInputs}
     />
```
Where am I going wrong?

**Comment by twisty** [comment]
Hello @stevematdavies Which part of this is using `formsy-react-components`? We don't have a `TextField` component.

**Comment by DanielTate** [comment]
For anyone having the issue I found This and it worked for me:
The issue is not with reactstrap but with the way you are managing the state which populates the values of the inputs.

this.setState({ todo: { [name]: value}});
When this code runs, it replaces this.state.todo with the new object you provide. This new object ends up having only 1 property. For example, when you check the checkbox, you are removing the title value. Also when you change the title, you are removing completed value.
When you remove the value, it becomes undefined and when an input value (or checkbox's checked) changes from a value to undefined it triggers this error. Also when it changes from undefined to a value, the same thing happens.

To fix this you need to spread the existing values in the new todo you are creating, only overriding the one you want to change.

this.setState({ todo: { ...this.state.todo, [name]: value } });
Demo: https://www.webpackbin.com/bins/-KqsH3Gto_LZBWEUvRj0

ORIGINAL LINK: https://github.com/reactstrap/reactstrap/issues/522

**Comment by SachaG** [comment]
In case it helps anyone, I just had the issue and solved it by changing `value={this.state.location}` to `value={this.state.location || ''}` (`this.state.location` can be empty).

**Comment by maximusunc** [comment]
@SachaG this worked for me. Thanks!

**Comment by ThaJay** [comment]
@SachaG works for checkbox as well :)
(vanilla React, google brought me here)

**Comment by sollych** [comment]
@SachaG Worked perfect.

**Comment by HDaghash** [comment]
Guys in your state just define the init value 

```
state = {
title : ' ' // init value for the input title 
}
```

**Comment by ThaJay** [comment]
it is props for me

**Comment by twisty** [comment]
Hello there, I'm going to lock down comments on this issue. There isn't really much to add that will help users of this package.

This page is ranking highly on google for the problem described, but I'm wary that more comments will add to the noise rather than the signal on this issue.

Happy coding ✊
